[[main]]
  name = "Home"
  url = "/"
  weight = 10

[[main]]
  name = "Spring Giveaway"
  url = "/spring-giveaway/"
  weight = 20

[[main]]
  name = "Fall Giveaway"
  url = "/fall-giveaway/"
  weight = 30

[[main]]
  name = "Kitchen Garden"
  url = "/kitchen-garden/"
  weight = 40

[[main]]
  name = "Garden Writing"
  url = "https://rediscoveringforgottenways.substack.com/"
  weight = 50
